import react from "@bya/config/eslint/react";

// next-env.d.ts is generated by `next build`/`next dev` and Next.js's own
// header says "This file should not be edited" — exclude it from lint.
export default [...react, { ignores: [".next/**", "next-env.d.ts"] }];
