import { ImageResponse } from "next/og";

/** Favicon — brand navy tile with the gold mark, generated by next/og. */
export const size = { width: 64, height: 64 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#0e1c12",
        borderRadius: 12,
        color: "#E9A23B",
        fontSize: 40,
        fontWeight: 800,
        fontFamily: "sans-serif",
      }}
    >
      B
    </div>,
    size,
  );
}
