import mongoose from "mongoose";
import { assertIndexes, connectDb, disconnectDb } from "../../config/db.js";
import { loadEnv } from "../../config/env.js";
// Importing the models registers them with Mongoose, which is what makes
// `assertIndexes` (a loop over `mongoose.models`) rebuild THEIR declared
// indexes — including the new unique `authUid` ones — after the rename.
import "../../models/accountant.model.js";
import "../../models/business.model.js";
import "../../models/lead.model.js";
import "../../models/user.model.js";

/**
 * Production data migration: rename the legacy identity field to `authUid`
 * on every collection that carries it, drop the old field's indexes, and
 * rebuild the declared ones.
 *
 * Run with: `pnpm --filter @bya/api migrate:auth-uid` (tsx; reads
 * MONGODB_URI via the same validated env loader the server boots with).
 *
 * ## Idempotent by construction — safe to re-run
 *
 * - `$rename` only touches documents that still HAVE the old field
 *   (filtered explicitly below, and `$rename` itself no-ops otherwise), so
 *   a second run reports `renamed: 0` and changes nothing.
 * - Old-field indexes are dropped only if present.
 * - `assertIndexes` (`syncIndexes`) converges to the models' declared index
 *   set no matter how often it runs.
 *
 * The one literal appearance of the legacy field name in this codebase is
 * the `$rename` source string here — it names data at rest, not code.
 */

/** The legacy field, exactly as it exists in production documents. */
const LEGACY_FIELD = "firebaseUid";
const NEW_FIELD = "authUid";

/** Every collection that carried the legacy identity field. */
const COLLECTIONS = ["users", "accountants", "businesses", "leads"] as const;

async function migrateCollection(name: string): Promise<void> {
  const collection = mongoose.connection.db?.collection(name);
  if (collection === undefined) {
    throw new Error(`no database handle for collection "${name}" — is the connection open?`);
  }

  const withLegacy = await collection.countDocuments({ [LEGACY_FIELD]: { $exists: true } });
  const result = await collection.updateMany(
    { [LEGACY_FIELD]: { $exists: true } },
    { $rename: { [LEGACY_FIELD]: NEW_FIELD } },
  );

  // Drop every index keyed on the old field. By name lookup over the live
  // index list, not a hardcoded name — Mongo's autogenerated names
  // (`firebaseUid_1`) are convention, not contract.
  const indexes = await collection.indexes();
  const stale = indexes.filter((index) => index.key !== undefined && LEGACY_FIELD in index.key);
  for (const index of stale) {
    if (index.name === undefined) continue;
    await collection.dropIndex(index.name);
    console.warn(`  ${name}: dropped stale index ${index.name}`);
  }

  console.warn(
    `  ${name}: ${withLegacy} document(s) carried ${LEGACY_FIELD}, renamed ${result.modifiedCount}`,
  );
}

async function main(): Promise<void> {
  const env = loadEnv();
  console.warn(`connecting to ${new URL(env.MONGODB_URI).host ?? "database"}…`);
  await connectDb(env.MONGODB_URI);

  try {
    for (const name of COLLECTIONS) {
      await migrateCollection(name);
    }

    // Rebuild the models' declared indexes — restores the unique `authUid`
    // constraints the dropped legacy indexes used to provide.
    console.warn("rebuilding declared indexes…");
    await assertIndexes();
    console.warn("done.");
  } finally {
    await disconnectDb();
  }
}

// Fail loud: a half-applied migration must exit non-zero, never look done.
main().catch((error: unknown) => {
  console.error("migration failed:", error);
  process.exitCode = 1;
});
